--------------------------------------------------------
--  DDL for Procedure GETNEWREP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "GETNEWREP" 
(
  P_QUEUEID IN QUEUE_DETAILS.QUEUEID%TYPE,
  P_REPNAME IN QUEUE_DETAILS.SALES_REP_ASSIGNED%TYPE
)
IS
  V_REPNAME QUEUE_DETAILS.SALES_REP_ASSIGNED%TYPE;
  V_STATUS QUEUE_DETAILS.STATUS%TYPE;
BEGIN
  
  
  SELECT STATUS,SALES_REP_ASSIGNED INTO V_STATUS,V_REPNAME FROM QUEUE_DETAILS WHERE QUEUEID=P_QUEUEID;
  UPDATE QUEUE_DETAILS SET SALES_REP_ASSIGNED = P_REPNAME, STATUS='WAITING'  WHERE QUEUEID=P_QUEUEID AND STATUS <>'CLOSE';
   
   IF(v_status='ASSISTING' ) then
    UPDATE SALES_REP_AVAILABILITY  SET ISAVAILABLE='AVAILABLE' WHERE FIRST_NAME=V_REPNAME;
  END IF;   

COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('ERROR!');
END  GETNEWREP;

/
