REM INSERTING into EXE_CUST
SET DEFINE OFF;
Insert into EXE_CUST (PHONE,FIRST_NAME,LAST_NAME,STATUS) values ('1111111111','Sachin','Tendulkar','ACTIVE');
Insert into EXE_CUST (PHONE,FIRST_NAME,LAST_NAME,STATUS) values ('2222222222','Virendra','Sehwag','ACTIVE');
Insert into EXE_CUST (PHONE,FIRST_NAME,LAST_NAME,STATUS) values ('3333333333','Saurabh','Ganguly','ACTIVE');
Insert into EXE_CUST (PHONE,FIRST_NAME,LAST_NAME,STATUS) values ('4444444444','Rahul','Dravid','ACTIVE');
