REM INSERTING into SALES_REP_AVAILABILITY
SET DEFINE OFF;
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (101,'Peter','Parker','1245639870','AVAILABLE','peter@abc.com','abc','MGR',111);
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (102,'Bruce','Wayne','4585455454','AVAILABLE','bruce@abc.com','abc','REP',111);
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (201,'Oliver','Green','5647896321','AVAILABLE','oliver@abc.com','abc','MGR',222);
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (202,'Clark','Kent','9865471230','AVAILABLE','clark@abc.com','abc','REP',222);
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (301,'Steve','Rogers','6895741230','AVAILABLE','steve@abc.com','abc','MGR',333);
Insert into SALES_REP_AVAILABILITY (SALES_REP_ID,FIRST_NAME,LAST_NAME,CONTACT_NO,ISAVAILABLE,EMAIL,PASSWORD,DESIG,STORE_ID) values (302,'Tony','Stark','7896584123','AVAILABLE','tony@abc.com','abc','REP',333);
