--------------------------------------------------------
--  DDL for Table QUEUE_DETAILS_HISTORY
--------------------------------------------------------

  CREATE TABLE "QUEUE_DETAILS_HISTORY" ("QUEUEID" NUMBER(10,0), "FNAME" VARCHAR2(45), "LNAME" VARCHAR2(45), "PHONE" VARCHAR2(45), "ARRIVAL_TIME" TIMESTAMP (6), "ASSIST_TIME" TIMESTAMP (6), "NA_TIME" TIMESTAMP (6), "CLOSE_TIME" TIMESTAMP (6), "SALES_REP_ASSIGNED" VARCHAR2(50) DEFAULT 'NEXT AVAILABLE', "QDATE" DATE, "REASON" VARCHAR2(50), "STORE_ID" NUMBER) ;
