--------------------------------------------------------
--  DDL for Table QUEUE_DETAILS
--------------------------------------------------------

  CREATE TABLE "QUEUE_DETAILS" ("QUEUEID" NUMBER(10,0), "FNAME" VARCHAR2(45), "LNAME" VARCHAR2(45), "PHONE" VARCHAR2(45), "REASON" VARCHAR2(100), "TYPE" VARCHAR2(100), "QCOMMENT" VARCHAR2(100), "QDATE" TIMESTAMP (6), "SALES_REP_ASSIGNED" VARCHAR2(50) DEFAULT 'NEXT AVAILABLE', "STATUS" VARCHAR2(20), "NA_COUNT" NUMBER(10,0) DEFAULT 0, "STORE_ID" NUMBER) ;
